# Generated by Django 5.2.17 on 2026-09-17 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_busqueda_sin_tildes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('texto', models.TextField(verbose_name='nota')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_socios', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='socios.socio', verbose_name='socio')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha', '-creada'],
            },
        ),
    ]
