# Generated by Django 5.2.16 on 2026-08-14 16:08

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.socios.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['socio__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre completo')),
                ('dni', apps.socios.fields.DNIField(error_messages={'unique': 'Ya hay un socio dado de alta con este DNI.'}, help_text='DNI o NIE, con la letra', max_length=9, unique=True, verbose_name='DNI')),
                ('teléfono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Escribe un teléfono válido: 600 123 456, o con prefijo (+34 600 123 456).', regex='^\\+?\\d[\\d\\s.-]{7,}$')], verbose_name='teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('días_semana', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')]), help_text='Días en los que se imparte el curso', size=7, verbose_name='días de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='hora de fin')),
                ('profesor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_impartidos', to=settings.AUTH_USER_MODEL, verbose_name='profesor principal')),
                ('profesores_sustitutos', models.ManyToManyField(blank=True, help_text='Además del principal, quienes pueden dar este curso', related_name='cursos_sustituidos', to=settings.AUTH_USER_MODEL, verbose_name='profesores sustitutos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['días_semana', 'hora_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='hora de inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la clase')),
                ('asistentes', models.ManyToManyField(blank=True, related_name='clases_asistidas', to='clases.alumno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases_impartidas', to=settings.AUTH_USER_MODEL, verbose_name='profesor')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='clases.curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursos',
            field=models.ManyToManyField(related_name='alumnos', to='clases.curso', verbose_name='cursos'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='socio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='alumno', to='clases.socio', verbose_name='socio'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='curso_hora_fin_posterior_a_inicio'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(condition=models.Q(('fin__isnull', True)), fields=('profesor',), name='una_clase_abierta_por_profesor', violation_error_message='Este profesor ya tiene una clase empezada sin terminar.'),
        ),
    ]
