# Generated by Django 5.2.16 on 2026-08-03 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_cursos_y_profesores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesores_sustitutos',
            field=models.ManyToManyField(blank=True, help_text='Además del principal, quienes pueden dar este curso', related_name='cursos_sustituidos', to=settings.AUTH_USER_MODEL, verbose_name='profesores sustitutos'),
        ),
    ]
