# Generated by Django 5.2.16 on 2026-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_cursos_y_profesores'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='acepta_inscripción',
            field=models.BooleanField(default=False, help_text='Comprendo que la inscripción es un requisito administrativo para participar en actividades y que no implica cargos de gestión ni responsabilidades internas.', verbose_name='Acepto mi inscripción como socia/o de la asociación'),
        ),
        migrations.AddField(
            model_name='socio',
            name='acepta_tratamiento_datos',
            field=models.BooleanField(default=False, help_text='Autorizo a la Asociación Cultural Botarate a tratar mis datos personales conforme a la normativa vigente y a almacenarlos mientras exista relación entre la asociación y mi participación en sus actividades.', verbose_name='Acepto el tratamiento de mis datos personales'),
        ),
        migrations.AddField(
            model_name='socio',
            name='quiere_comunicaciones',
            field=models.BooleanField(blank=True, default=False, help_text='Autorizo a Botarate a enviarme comunicaciones informativas sobre actividades culturales.', verbose_name='Quiero recibir información sobre cursos, talleres y actividades'),
        ),
        migrations.AddField(
            model_name='socio',
            name='quiere_whatsapp',
            field=models.BooleanField(blank=True, default=False, help_text='Acepto ser añadida/o al grupo de WhatsApp para recibir avisos y participar en la comunidad interna.', verbose_name='Quiero unirme a la comunidad de WhatsApp de Botarate'),
        ),
    ]
