# Generated by Django 5.2.17 on 2026-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0007_rescate_de_socios_sin_nif'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='reporte',
            field=models.TextField(blank=True, help_text='Indica aquí cualquier cosa extraordinaria que haya pasado en clase', null=True),
        ),
    ]
