# Generated by Django 5.2.17 on 2026-09-11 08:12

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0008_clase_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('CLASE', 'Una clase'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], max_length=10, verbose_name='modalidad')),
                ('desde', models.DateField(help_text='Primer día que cubre el pago; en una clase suelta, el día de la clase.', verbose_name='desde')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe (€)')),
                ('forma_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia bancaria'), ('EFECTIVO', 'Efectivo'), ('BIZUM', 'Bizum'), ('DATAFONO', 'Datáfono')], max_length=13, verbose_name='forma de pago')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de pago')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clases.alumno', verbose_name='alumna')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clases.curso', verbose_name='curso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='pago_importe_positivo')],
            },
        ),
    ]
